@extends('layouts.tenant')

@section('title', 'سلفي')
@section('page-title', 'سلفي')

@section('content')
<style>
    .loan-self-page { direction: rtl; }
    .loan-self-table th, .loan-self-table td { white-space: nowrap; vertical-align: middle; }
    .loan-empty { padding: 55px 20px !important; text-align: center; color: #64748b; }
    .loan-actions { display: flex; gap: 5px; flex-wrap: wrap; }
    .loan-money { direction: ltr; display: inline-block; font-weight: 700; }
    .summary-box { height: 100%; padding: 15px; border: 1px solid #e2e8f0; border-radius: 14px; background: #f8fafc; }
    .summary-box small { display: block; color: #64748b; margin-bottom: 6px; }
    body.ry-modal-open { overflow: hidden !important; }
    .ry-modal { position: fixed; inset: 0; z-index: 99999; display: none; align-items: center; justify-content: center; padding: 24px; overflow-y: auto; background: rgba(15,23,42,.68); }
    .ry-modal-panel { width: min(900px,100%); max-height: calc(100vh - 48px); display: flex; flex-direction: column; overflow: hidden; background: #fff; border-radius: 20px; box-shadow: 0 25px 70px rgba(15,23,42,.28); }
    .ry-modal-panel.small { width: min(520px,100%); }
    .ry-modal-header,.ry-modal-footer { flex: 0 0 auto; padding: 18px 22px; background:#fff; }
    .ry-modal-header { border-bottom:1px solid #e9ecef; } .ry-modal-footer { border-top:1px solid #e9ecef; }
    .ry-modal-body { flex:1 1 auto; min-height:0; padding:22px; overflow:auto; }
    .ry-modal-close { width:40px;height:40px;border:0;border-radius:12px;background:#f1f5f9;color:#334155;font-size:24px;line-height:1; }
    .pagination-box { display:flex;justify-content:space-between;align-items:center;gap:12px;flex-wrap:wrap; }
    .page-buttons { display:flex;gap:5px;direction:ltr; }
    @media(max-width:767.98px){.ry-modal{padding:8px;align-items:stretch}.ry-modal-panel{max-height:calc(100vh - 16px);border-radius:14px}.ry-modal-header,.ry-modal-footer,.ry-modal-body{padding:15px}}
</style>

<div class="loan-self-page">
    <div id="pageAlert" class="alert mb-4 d-none"></div>
    <div class="card border-0 shadow-sm rounded-4 mb-4"><div class="card-body p-4"><div class="d-flex justify-content-between align-items-center gap-3 flex-wrap"><div><h5 class="mb-2">سلفي المالية</h5><p class="text-muted mb-0">قدّم طلب سلفة وتابع حالة الاعتماد والأقساط المتبقية.</p></div><button class="btn btn-primary px-4" id="btnCreate" type="button">+ طلب سلفة جديد</button></div></div></div>

    <div class="card border-0 shadow-sm rounded-4 mb-4"><div class="card-body p-4"><form id="filterForm"><div class="row g-3 align-items-end"><div class="col-md-5"><label class="form-label">الحالة</label><select class="form-select" id="filterStatus"><option value="">جميع الحالات</option><option value="draft">مسودة</option><option value="submitted">بانتظار الاعتماد</option><option value="approved">معتمدة</option><option value="active">قيد السداد</option><option value="completed">مكتملة</option><option value="rejected">مرفوضة</option><option value="cancelled">ملغاة</option></select></div><div class="col-md-3"><label class="form-label">عدد السجلات</label><select class="form-select" id="perPage"><option value="10" selected>10</option><option value="20">20</option><option value="50">50</option></select></div><div class="col-md-4"><div class="d-flex gap-2"><button class="btn btn-primary flex-grow-1" type="submit">تطبيق</button><button class="btn btn-light border" id="btnReset" type="button">إعادة</button></div></div></div></form></div></div>

    <div class="card border-0 shadow-sm rounded-4"><div class="card-header bg-white border-0 p-4"><div class="d-flex justify-content-between"><div><h6 class="mb-1">طلبات السلف</h6><small class="text-muted" id="recordsSummary">جاري التحميل...</small></div><span class="badge bg-primary-subtle text-primary px-3 py-2" id="recordsCount">0 طلب</span></div></div><div class="table-responsive"><table class="table table-hover loan-self-table mb-0"><thead class="table-light"><tr><th>#</th><th>رقم الطلب</th><th>النوع</th><th>المطلوب</th><th>المعتمد</th><th>المدفوع</th><th>المتبقي</th><th>الحالة</th><th>الإجراءات</th></tr></thead><tbody id="tableBody"><tr><td colspan="9" class="loan-empty text-primary">جاري تحميل البيانات...</td></tr></tbody></table></div><div class="card-footer bg-white border-0 p-4"><div class="pagination-box"><small class="text-muted" id="paginationSummary"></small><div class="page-buttons" id="pageButtons"></div></div></div></div>
</div>

<div class="ry-modal" id="formModal"><div class="ry-modal-panel"><div class="ry-modal-header"><div class="d-flex justify-content-between align-items-center"><div><h5 class="mb-1" id="formTitle">طلب سلفة جديد</h5><small class="text-muted" id="employeeName"></small></div><button class="ry-modal-close close-form" type="button">×</button></div></div><form id="loanForm"><div class="ry-modal-body"><div id="formAlert" class="alert alert-danger d-none"></div><input type="hidden" id="loanUuid"><div class="row g-3">
    <div class="col-md-6"><label class="form-label">نوع السلفة <span class="text-danger">*</span></label><select class="form-select" id="loanType" required><option value="">اختر النوع</option></select><div class="invalid-feedback" data-error-for="loan_type"></div></div>
    <div class="col-md-6"><label class="form-label">المبلغ المطلوب <span class="text-danger">*</span></label><div class="input-group"><input type="number" class="form-control" id="requestedAmount" min="1" step="0.01" required><span class="input-group-text">ر.س</span></div><div class="invalid-feedback" data-error-for="requested_amount"></div></div>
    <div class="col-md-6"><label class="form-label">عدد الأقساط المقترح <span class="text-danger">*</span></label><input type="number" class="form-control" id="installmentsCount" min="1" max="60" value="1" required><div class="invalid-feedback" data-error-for="installments_count"></div></div>
    <div class="col-md-6"><label class="form-label">تاريخ أول قسط المقترح</label><input type="date" class="form-control" id="firstDate"><div class="invalid-feedback" data-error-for="first_installment_date"></div></div>
    <div class="col-12"><div class="alert alert-primary py-2 mb-0" id="installmentPreview">القسط التقديري: 0.00 ر.س</div></div>
    <div class="col-12"><label class="form-label">سبب طلب السلفة <span class="text-danger">*</span></label><textarea class="form-control" id="reason" rows="3" maxlength="2000" required></textarea><div class="invalid-feedback" data-error-for="reason"></div></div>
    <div class="col-12"><label class="form-label">ملاحظات إضافية</label><textarea class="form-control" id="notes" rows="2" maxlength="3000"></textarea><div class="invalid-feedback" data-error-for="employee_notes"></div></div>
</div></div><div class="ry-modal-footer"><div class="d-flex justify-content-end gap-2"><button class="btn btn-light border close-form" type="button">إلغاء</button><button class="btn btn-primary px-4" id="btnSave" type="submit">حفظ المسودة</button></div></div></form></div></div>

<div class="ry-modal" id="detailsModal"><div class="ry-modal-panel"><div class="ry-modal-header"><div class="d-flex justify-content-between align-items-center"><div><h5 class="mb-1">تفاصيل السلفة</h5><small class="text-muted" id="detailsNumber"></small></div><button class="ry-modal-close close-details" type="button">×</button></div></div><div class="ry-modal-body" id="detailsBody"></div><div class="ry-modal-footer"><div class="d-flex justify-content-end"><button class="btn btn-light border close-details" type="button">إغلاق</button></div></div></div></div>

<div class="ry-modal" id="confirmModal"><div class="ry-modal-panel small"><div class="ry-modal-header"><div class="d-flex justify-content-between align-items-center"><h5 class="mb-0" id="confirmTitle"></h5><button class="ry-modal-close close-confirm" type="button">×</button></div></div><div class="ry-modal-body"><p class="mb-0" id="confirmMessage"></p></div><div class="ry-modal-footer"><div class="d-flex justify-content-end gap-2"><button class="btn btn-light border close-confirm" type="button">تراجع</button><button class="btn btn-danger" id="btnConfirm" type="button">تأكيد</button></div></div></div></div>
@endsection

@push('scripts')
<script>
(function(){
    'use strict';
    const urls={
        data:@json(route('app.self-service.loans.data')),
        options:@json(route('app.self-service.loans.options')),
        store:@json(route('app.self-service.loans.store')),
        show:@json(route('app.self-service.loans.show','__UUID__')),
        update:@json(route('app.self-service.loans.update','__UUID__')),
        destroy:@json(route('app.self-service.loans.destroy','__UUID__')),
        submit:@json(route('app.self-service.loans.submit','__UUID__')),
        cancel:@json(route('app.self-service.loans.cancel','__UUID__'))
    };
    const state={page:1,pending:null};
    const csrf=()=>$('meta[name="csrf-token"]').attr('content');
    const routeUrl=(url,uuid)=>url.replace('__UUID__',encodeURIComponent(uuid));
    const esc=value=>$('<div>').text(value??'').html();
    const money=value=>Number(value??0).toLocaleString('ar-SA',{minimumFractionDigits:2,maximumFractionDigits:2});
    function openModal(id){$(id).css('display','flex');$('body').addClass('ry-modal-open')}
    function closeModal(id){$(id).hide();if(!$('.ry-modal:visible').length)$('body').removeClass('ry-modal-open')}
    function pageAlert(message,type='success'){$('#pageAlert').removeClass('d-none alert-success alert-danger').addClass('alert-'+type).text(message);window.scrollTo({top:0,behavior:'smooth'})}
    function statusBadge(item){const colors={draft:'secondary',submitted:'warning',approved:'primary',active:'info',completed:'success',rejected:'danger',cancelled:'dark'},color=colors[item.status]??'secondary';return '<span class="badge bg-'+color+'-subtle text-'+color+'">'+esc(item.status_label)+'</span>'}
    function requestError(xhr,form=false){const data=xhr.responseJSON??{},message=data.message??'تعذر تنفيذ العملية.';if(!form){pageAlert(message,'danger');return}$('#formAlert').removeClass('d-none').text(message);Object.entries(data.errors??{}).forEach(([field,messages])=>{$('[data-error-for="'+field+'"]').text(Array.isArray(messages)?messages[0]:messages).closest('[class*="col-"]').find('input,select,textarea').first().addClass('is-invalid')})}
    function clearErrors(){$('#formAlert').addClass('d-none').empty();$('#loanForm .is-invalid').removeClass('is-invalid');$('[data-error-for]').empty()}
    function loadOptions(){return $.getJSON(urls.options).done(response=>{const data=response.data??response;$('#employeeName').text(data.employee?.name??'');$('#loanType').html('<option value="">اختر النوع</option>');(data.loan_types??[]).forEach(x=>$('#loanType').append('<option value="'+esc(x.value)+'">'+esc(x.label)+'</option>'))}).fail(xhr=>requestError(xhr))}
    function loadData(page=1){state.page=page;$('#tableBody').html('<tr><td colspan="9" class="loan-empty text-primary">جاري تحميل البيانات...</td></tr>');$.getJSON(urls.data,{page,status:$('#filterStatus').val(),per_page:$('#perPage').val()}).done(response=>{renderRows(response.data??[]);renderPages(response.meta??{})}).fail(xhr=>{$('#tableBody').html('<tr><td colspan="9" class="loan-empty text-danger">تعذر تحميل البيانات.</td></tr>');requestError(xhr)})}
    function renderRows(items){if(!items.length){$('#tableBody').html('<tr><td colspan="9" class="loan-empty">لا توجد طلبات سلف.</td></tr>');return}const start=(state.page-1)*Number($('#perPage').val());$('#tableBody').html(items.map((item,i)=>{let actions='<button class="btn btn-sm btn-outline-primary btn-view" data-uuid="'+item.uuid+'">عرض</button>';if(item.can_edit)actions+='<button class="btn btn-sm btn-outline-secondary btn-edit" data-uuid="'+item.uuid+'">تعديل</button>';if(item.can_submit)actions+='<button class="btn btn-sm btn-success btn-submit" data-uuid="'+item.uuid+'" data-number="'+esc(item.request_number)+'">إرسال</button>';if(item.can_cancel)actions+='<button class="btn btn-sm btn-outline-danger btn-cancel" data-uuid="'+item.uuid+'" data-number="'+esc(item.request_number)+'">إلغاء</button>';if(item.status==='draft')actions+='<button class="btn btn-sm btn-danger btn-delete" data-uuid="'+item.uuid+'" data-number="'+esc(item.request_number)+'">حذف</button>';return '<tr><td>'+(start+i+1)+'</td><td dir="ltr">'+esc(item.request_number)+'</td><td>'+esc(item.loan_type_label)+'</td><td><span class="loan-money">'+money(item.requested_amount)+'</span></td><td><span class="loan-money">'+(item.approved_amount==null?'—':money(item.approved_amount))+'</span></td><td><span class="loan-money">'+money(item.paid_amount)+'</span></td><td><span class="loan-money">'+money(item.remaining_amount)+'</span></td><td>'+statusBadge(item)+'</td><td><div class="loan-actions">'+actions+'</div></td></tr>'}).join(''))}
    function renderPages(meta){const total=Number(meta.total??0),current=Number(meta.current_page??1),last=Number(meta.last_page??1),per=Number(meta.per_page??10);$('#recordsCount').text(total+' طلب');$('#recordsSummary').text(total?'عرض '+(((current-1)*per)+1)+' إلى '+Math.min(current*per,total)+' من '+total:'لا توجد سجلات');$('#paginationSummary').text('الصفحة '+current+' من '+last);let html='<button class="btn btn-sm btn-light border page-btn" data-page="'+(current-1)+'" '+(current<=1?'disabled':'')+'>السابق</button>';for(let p=Math.max(1,current-2);p<=Math.min(last,current+2);p++)html+='<button class="btn btn-sm '+(p===current?'btn-primary':'btn-light border')+' page-btn" data-page="'+p+'">'+p+'</button>';html+='<button class="btn btn-sm btn-light border page-btn" data-page="'+(current+1)+'" '+(current>=last?'disabled':'')+'>التالي</button>';$('#pageButtons').html(html)}
    function resetForm(){$('#loanForm')[0].reset();$('#loanUuid').val('');$('#installmentsCount').val(1);$('#formTitle').text('طلب سلفة جديد');$('#btnSave').text('حفظ المسودة');clearErrors();preview()}
    function preview(){const amount=Number($('#requestedAmount').val()||0),count=Math.max(1,Number($('#installmentsCount').val()||1));$('#installmentPreview').text('القسط التقديري: '+money(amount/count)+' ر.س')}
    function payload(){return{_token:csrf(),loan_type:$('#loanType').val(),requested_amount:$('#requestedAmount').val(),installments_count:$('#installmentsCount').val(),first_installment_date:$('#firstDate').val()||null,reason:$('#reason').val(),employee_notes:$('#notes').val()||null}}
    function confirmAction(title,message,label,style,callback){state.pending=callback;$('#confirmTitle').text(title);$('#confirmMessage').text(message);$('#btnConfirm').removeClass('btn-danger btn-success btn-primary').addClass(style).text(label);openModal('#confirmModal')}
    function details(item){let schedule='<p class="text-muted">لم يتم إنشاء الأقساط بعد.</p>';if(item.installments?.length)schedule='<div class="table-responsive"><table class="table"><thead class="table-light"><tr><th>#</th><th>الاستحقاق</th><th>المبلغ</th><th>المسدد</th><th>المتبقي</th><th>الحالة</th></tr></thead><tbody>'+item.installments.map(x=>'<tr><td>'+x.installment_number+'</td><td>'+esc(x.due_date)+'</td><td>'+money(x.amount)+'</td><td>'+money(x.paid_amount)+'</td><td>'+money(x.remaining_amount)+'</td><td>'+esc(x.status_label)+'</td></tr>').join('')+'</tbody></table></div>';return '<div class="row g-3 mb-4"><div class="col-md-3"><div class="summary-box"><small>المطلوب</small><strong>'+money(item.requested_amount)+' ر.س</strong></div></div><div class="col-md-3"><div class="summary-box"><small>المعتمد</small><strong>'+(item.approved_amount==null?'—':money(item.approved_amount)+' ر.س')+'</strong></div></div><div class="col-md-3"><div class="summary-box"><small>المدفوع</small><strong>'+money(item.paid_amount)+' ر.س</strong></div></div><div class="col-md-3"><div class="summary-box"><small>المتبقي</small><strong>'+money(item.remaining_amount)+' ر.س</strong></div></div></div><h6>سبب الطلب</h6><div class="p-3 bg-light rounded-3 mb-3">'+esc(item.reason)+'</div>'+(item.approval_notes?'<div class="alert alert-success">ملاحظات الاعتماد: '+esc(item.approval_notes)+'</div>':'')+(item.rejection_reason?'<div class="alert alert-danger">سبب الرفض: '+esc(item.rejection_reason)+'</div>':'')+(item.cancellation_reason?'<div class="alert alert-secondary">سبب الإلغاء: '+esc(item.cancellation_reason)+'</div>':'')+'<h6 class="mt-4">جدول الأقساط</h6>'+schedule}

    $(function(){loadOptions();loadData();$('#filterForm').on('submit',e=>{e.preventDefault();loadData(1)});$('#btnReset').on('click',()=>{$('#filterForm')[0].reset();$('#perPage').val('10');loadData(1)});$(document).on('click','.page-btn:not(:disabled)',function(){loadData(Number($(this).data('page')))});$('#btnCreate').on('click',()=>{resetForm();openModal('#formModal')});$('#requestedAmount,#installmentsCount').on('input',preview);$('.close-form').on('click',()=>closeModal('#formModal'));$('.close-details').on('click',()=>closeModal('#detailsModal'));$('.close-confirm').on('click',()=>{state.pending=null;closeModal('#confirmModal')});$('.ry-modal').on('click',function(e){if(e.target===this)closeModal('#'+this.id)});
        $('#loanForm').on('submit',function(e){e.preventDefault();clearErrors();const uuid=$('#loanUuid').val(),isEdit=uuid!=='';const data=payload();if(isEdit)data._method='PUT';const $btn=$('#btnSave').prop('disabled',true).text('جاري الحفظ...');$.ajax({url:isEdit?routeUrl(urls.update,uuid):urls.store,method:'POST',data}).done(response=>{closeModal('#formModal');pageAlert(response.message);loadData(isEdit?state.page:1)}).fail(xhr=>requestError(xhr,true)).always(()=>$btn.prop('disabled',false).text(isEdit?'حفظ التعديلات':'حفظ المسودة'))});
        $(document).on('click','.btn-edit',function(){resetForm();$.getJSON(routeUrl(urls.show,$(this).data('uuid'))).done(response=>{const item=response.data??response;$('#loanUuid').val(item.uuid);$('#formTitle').text('تعديل مسودة السلفة');$('#btnSave').text('حفظ التعديلات');$('#loanType').val(item.loan_type);$('#requestedAmount').val(item.requested_amount);$('#installmentsCount').val(item.installments_count);$('#firstDate').val(item.first_installment_date??'');$('#reason').val(item.reason);$('#notes').val(item.employee_notes??'');preview();openModal('#formModal')}).fail(xhr=>requestError(xhr))});
        $(document).on('click','.btn-view',function(){$.getJSON(routeUrl(urls.show,$(this).data('uuid'))).done(response=>{const item=response.data??response;$('#detailsNumber').text(item.request_number+' - '+item.status_label);$('#detailsBody').html(details(item));openModal('#detailsModal')}).fail(xhr=>requestError(xhr))});
        $(document).on('click','.btn-submit',function(){const uuid=$(this).data('uuid'),number=$(this).data('number');confirmAction('إرسال الطلب','هل تريد إرسال السلفة "'+number+'" للاعتماد؟ لن يمكن تعديلها بعد الإرسال.','إرسال','btn-success',()=>$.post(routeUrl(urls.submit,uuid),{_token:csrf()}).done(response=>{closeModal('#confirmModal');pageAlert(response.message);loadData(state.page)}).fail(xhr=>requestError(xhr)))});
        $(document).on('click','.btn-cancel',function(){const uuid=$(this).data('uuid'),number=$(this).data('number');confirmAction('إلغاء السلفة','هل تريد إلغاء طلب السلفة "'+number+'"؟','إلغاء الطلب','btn-danger',()=>$.post(routeUrl(urls.cancel,uuid),{_token:csrf(),cancellation_reason:'ألغيت بواسطة الموظف'}).done(response=>{closeModal('#confirmModal');pageAlert(response.message);loadData(state.page)}).fail(xhr=>requestError(xhr)))});
        $(document).on('click','.btn-delete',function(){const uuid=$(this).data('uuid'),number=$(this).data('number');confirmAction('حذف المسودة','هل تريد حذف المسودة "'+number+'" نهائيًا؟','حذف','btn-danger',()=>$.ajax({url:routeUrl(urls.destroy,uuid),method:'POST',data:{_token:csrf(),_method:'DELETE'}}).done(response=>{closeModal('#confirmModal');pageAlert(response.message);loadData(state.page)}).fail(xhr=>requestError(xhr)))});
        $('#btnConfirm').on('click',function(){if(typeof state.pending!=='function')return;const callback=state.pending;state.pending=null;const $btn=$(this),label=$btn.text();$btn.prop('disabled',true).text('جاري التنفيذ...');const request=callback();if(request?.always)request.always(()=>$btn.prop('disabled',false).text(label));else $btn.prop('disabled',false).text(label)});
    });
})();
</script>
@endpush
